site_name: Cloudbreak 
site_favicon: /images/favicon.png
site_url: http://hortonworks.github.io/cloudbreak-documentation/
repo_url: https://github.com/hortonworks/cloudbreak-documentation
theme_dir: mkdocs_theme
theme_dir: custom_cinder
extra_css:
  - css/extra.css
dev_addr: 0.0.0.0:8000
strict: true
copyright: Â© 2011-2017 <a href="http://www.hortonworks.com" target="_blank">Hortonworks Inc</a>. All Rights Reserved. | <a href="http://hortonworks.com/privacy-policy/" target="_blank">Privacy Policy</a>
google_analytics: ['UA-22950817-24', 'auto']
markdown_extensions:
  - markdown_include.include
use_directory_urls: false
pages:
    - Get Started:
      - Introduction: index.md
      - Architecture: architecture.md
    - AWS:
      - Launch on AWS: aws-launch.md
      - Create a Cluster: aws-create.md
      - Access Cluster: aws-clusters-access.md
      - Manage and Monitor Clusters: aws-clusters-manage.md
      - Access Data on S3: aws-data.md
    - Azure:
      - Launch on Azure: azure-launch.md
      - Create a Cluster: azure-create.md
      - Access Cluster: azure-clusters-access.md
      - Manage and Monitor Clusters: azure-clusters-manage.md
      - Access Data on Azure: azure-data.md
    - GCP:
      - Launch on GCP: gcp-launch.md
      - Create a Cluster: gcp-create.md
      - Access Cluster: gcp-clusters-access.md
      - Manage and Monitor Clusters: gcp-clusters-manage.md
    - OpenStack:
      - Launch on Open Stack: os-launch.md
      - Create a Cluster: os-create.md
      - Access Cluster: os-clusters-access.md
      - Manage and Monitor Clusters: os-clusters-manage.md
    - Using Cloudbreak:
      - Advanced Cluster Options:
        - Blueprints: blueprints.md
        - Recipes: recipes.md
        - Resource Tagging: tags.md 
        - Custom Images: images.md
      - Managing Cloudbreak:
        - Install on Your Own VM: vm-launch.md
        - Upgrade Clodbreak: upgrade.md
        - Delete Cloudbreak: delete.md  
        - Configure Cloudbreak: profile.md
        - Manage Cloudbreak Credentials: credentials.md 
        - Manage Cloudbreak Database: cb-db.md
      - Security: 
        - Security Overview: security.md
        - Configure Basic Security: security-cb.md
        - Configure Kerberos: security-kerberos.md
      - CLI: 
        - Install the CLI: cli-install.md
        - Using the CLI: cli-using.md
      - Troubleshooting: 
        - General Troubleshooting: trouble-cb.md
        - Troubleshooting AWS: trouble-aws.md
        - Troubleshooting Azure: trouble-azure.md
        - Troubleshooting GCP: trouble-gcp.md
        - Troubleshooting OpenStack: trouble-os.md
      - Developer:
        - Developer Docs: dev.md
        - Cloudbreak SPI: dev-spi.md
        - Cloudbreak APIs: dev-api.md
        - Flow Diagrams: dev-flows.md 
    - More:
      - Release Notes: releasenotes.md
      - FAQs: faq.md 
      - Getting Help: get-help.md
      - SmartSense: smartsense.md

